# You can specify a custom docker image from Docker Hub as your build environment.
image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          # https://docs.gradle.org/current/userguide/gradle_wrapper.html
          - bash ./gradlew build -PspringProfiles=ci
  branches:
    staging:
      - step:
          name: Deploy to AWS
          deployment: staging
          caches:
            - gradle
          script:
            - bash ./gradlew build -PspringProfiles=ci
            - scp $BUILD_JAR $DEPLOY_USER@$DEPLOY_STAGING_HOST:$DEPLOY_PATH
            - ssh $DEPLOY_USER@$DEPLOY_STAGING_HOST "./deploy.sh"
