
logging:
  level:
    dev.zhihexireng: debug

mariocash.node:
  grpc.host: "localhost"
  grpc.port: 9090
  max-peers: 25

management:
  endpoint.health.show-details: always
  health:
    diskspace:
      enabled: false

spring:
  output:
    ansi:
      enabled: always
