version: '3'

services:
  node1:
    image: zhihexireng/mariocash-node
    container_name: node1
    ports:
    - 8080:8080
    - 9090:9090
    environment:
    - MARIOCASH_NODE_GRPC_HOST=node1
  node2:
    image: zhihexireng/mariocash-node
    container_name: node2
    ports:
    - 8081:8080
    environment:
    - MARIOCASH_NODE_GRPC_HOST=node2
