version: '3'

services:
  node1:
    image: zhihexireng/mariocash-node
    container_name: mariocash-node1
    ports:
    - 8080:8080
    - 9090:9090
    environment:
    - MARIOCASH_NODE_GRPC_HOST=node1
    - MARIOCASH_NODE_MAX_PEERS=25
  node2:
    image: zhihexireng/mariocash-node
    container_name: mariocash-node2
    ports:
    - 8081:8080
    environment:
    - MARIOCASH_NODE_GRPC_HOST=node2
    - RUN_SLEEP=3
